### ISSUE TITLE
error: 'ping_option' does not name a type

### ISSUE THREAD

**Issue by m510** [dvarrel/ESP_Ping#5]
Hello, I am trying to ping devices on my lan. I am using a Wemos D1R2 and platformio. With the las release of ESPping I got the following error con compile: 
\libdeps\d1_mini\ESPping\src/ESPping.h:63:12: error: 'ping_option' does not name a type
   63 |     static ping_option _options;
      |            ^~~~~~~~~~~
*** [.pio\build\d1_mini\src\Ping.ino.cpp.o] Error 1

**Comment by dvarrel** [comment]
Hi,
release 1.0.2 compile with arduino ide 2.0 and wemos d1 r2 & mini ( esp8266 hardware package 3.1.2 ) 

ping_option is from esp8266 hardware package : witch release have you  install in platformio ?

**Comment by pyprism** [comment]
Hello, I am also facing same issue. I have installed `dvarrel/ESPping@^1.0.2` from platformio.

**Comment by dvarrel** [comment]
compiling well with arduino ide

ping_option is defined in ping.h,,  libraries from esp8266 sdk

**Comment by pyprism** [comment]
I am trying from platformio , maybe there is a problem with platformio or this library is not compatible with platformio

**Comment by puhycz** [comment]
I have save problem on platfotrmio, dvarrel/ESPping@^1.0.2 In file included from src\main.cpp:13:
.pio\libdeps\esp8266\ESPping\src/ESPping.h:63:5: error: 'ping_option' does not name a type
   63 |     ping_option _options;

**Comment by Advocate-Sandeep-Prakash** [comment]
I have the same problem on platformio while compiling for ESP8266 related hardware. I tried for NodeMCU.
It compiles flawlessly for ESP32 related hardware. I tried for S2 Mini.

NOTE: Problem does not exist in Ardruino IDE. It is only in PlatformIO.

**Comment by Advocate-Sandeep-Prakash** [comment]
Solved the issue. The reason compilation failed for ESP8266 related hardware was because "ping.h" was not being taken from the ESP8266 SDK library. It was always taking the [ping.h](https://github.com/dvarrel/ESPping/blob/main/src/ping.h) in the [src](https://github.com/dvarrel/ESPping/tree/main/src) folder which has definitions only for ESP32.

Rename the [ping.h](https://github.com/dvarrel/ESPping/blob/main/src/ping.h) in the [src](https://github.com/dvarrel/ESPping/tree/main/src) folder to ping32.h and change the #include references accordingly. Then it works. Checked it in PlatformIO both for S2 mini and NodeMCU.

NOTE: I haven't checked it in Arduino IDE.

@dvarrel You might have to rename the file or any other better way.

**Comment by dvarrel** [comment]
fine, i've renamed ping.h to ping32.h and dependency. no change in arduino IDE. is  it ok with platformio ?

**Comment by Advocate-Sandeep-Prakash** [comment]
Checked for S2 mini and NodeMCU hardware. It works.

NOTE: Had to use `https://github.com/dvarrel/ESPping @ ^1.0.3` as the propagation of the update was taking time.

@dvarrel Thank you
